#ifndef DISPLAYCAL_H
#define DISPLAYCAL_H

#define DISPLAYCAL_DEFAULT_ENABLED 1
#define DISPLAYCAL_DEFAULT_RED_GAIN 1.0
#define DISPLAYCAL_DEFAULT_GREEN_GAIN 0.92
#define DISPLAYCAL_DEFAULT_BLUE_GAIN 0.58

#define DISPLAYCAL_GAIN_SCALE 100
#define DISPLAYCAL_GAIN_MIN 0
#define DISPLAYCAL_GAIN_MAX 200

#endif
