---
name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - tg5040

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup
        run: make setup
        
      - name: Build ${{ matrix.toolchain }}
        run: make ${{ matrix.toolchain }}

      - name: Special
        run: make special

      - name: Package
        run: make package
