---
name: CI

on:
  push:
    branches:
      - main
      - build-in-ci
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - tg5040

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup
        run: make setup
        
      - name: Build ${{ matrix.toolchain }}
        run: make ${{ matrix.toolchain }}

      - name: Special
        run: make special

      - name: Package
        run: make package

      - name: List Generated Files
        run: ls -l releases

      - name: Upload All
        uses: actions/upload-artifact@v4.6.2
        with:
          name: NextUI-all-${{ matrix.toolchain }}.zip
          path: releases/NextUI-all.zip

      - name: Upload Base
        uses: actions/upload-artifact@v4.6.2
        with:
          name: NextUI-base-${{ matrix.toolchain }}.zip
          path: releases/NextUI-base.zip

      - name: Upload Extras
        uses: actions/upload-artifact@v4.6.2
        with:
          name: NextUI-extras-${{ matrix.toolchain }}.zip
          path: releases/NextUI-extras.zip
